#!/bin/sh

if [ -z "$APP" ] ; then
  echo "Please precise the application to apply using APP=."
fi

for js in `find apps/$APP/js shared -name '*.js'` ; do
  awk -v file="$(basename $js)" '
    BEGIN {
      print "console.time(\"" file "\");"
      nested = 0;
    }

    END {
      print "console.timeEnd(\"" file "\");"
    }

    /init:\s*function/ {
      inInit = 1
      inInitFirstLine = 1
    }

    /{/ {
      if (inInit) {
        nested++
      }
    }

    /}/ {
      if (inInit) {
        nested--
        if (!nested) {
          print "console.timeEnd(\"" file ": init\");"
          inInit = 0;
        }
      }
    }

    {
      print
      if (inInitFirstLine) {
        print "console.time(\"" file ": init\");"
        inInitFirstLine = 0;
      }
    }
  ' $js > ${js}.tmp
  mv ${js}.tmp $js
done

